### ISSUE TITLE
Windows containers have a high latency on first outbound connection to internet

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#519]
On some windows containers, there is a delay in the outbound connection to the internet.

**Comment by jackwoodward** [comment]
is this the fix being tested https://github.com/JiangtianLi/acs-engine/commit/dbb2ee3b35528517e8a427d45b8622b8cc3f95c1  ?

**Comment by JiangtianLi** [comment]
@jackwoodward We have done the test and verified the issue is fixed.

**Comment by jackwoodward** [comment]
thanks i just tested as well and can confirm as well

**Comment by JiangtianLi** [comment]
@jackwoodward Thanks for confirming.

**Comment by JackQuincy** [comment]
closing as we have confirmation it is fixed

**Comment by jorgearteiro** [comment]
I am having same issue. I just created this cluster. Anyway to fix cluster manually.
It's a Windowsservercore image to VSTS agent. It tries connect mydomain.visualstudio.com to download agent.

2017-07-28T16:18:21.935352100Z 
 2017-07-28T16:18:21.935352100Z C:\BuildAgent>PowerShell.exe -ExecutionPolicy ByPass .\Start.ps1 
 2017-07-28T16:18:49.994239200Z Invoke-WebRequest : Unable to connect to the remote server
 2017-07-28T16:18:49.995422600Z At C:\BuildAgent\Start.ps1:40 char:13
 2017-07-28T16:18:49.995422600Z + $response = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri ...
 2017-07-28T16:18:49.995422600Z +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2017-07-28T16:18:49.995422600Z     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
 2017-07-28T16:18:49.995422600Z    pWebRequest) [Invoke-WebRequest], WebException
 2017-07-28T16:18:49.995422600Z     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
 2017-07-28T16:18:49.995422600Z    ll.Commands.InvokeWebRequestCommand
 2017-07-28T16:18:49.995422600Z

**Comment by brobichaud** [comment]
I too am seeing delays in outbound connectivity. I have a simple worker process that is in a tight loop checking a queue for messages and logging events to an external http based logging vendor. It's failing to connect (timeouts) at startup and for some short period of time. Either this bug is not yet fixed or a new and very similar one has crept in.

This is a big deal in my view.

**Comment by allenstecat** [comment]
I am also seeing delays in outbound communication on a new cluster. Looks like I may to grab a ETW event from the container to see what is blocking initial communication. Wonder if this has something to do with DNS as well
